name: Build and Deploy
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: nextsun/nextsun.github.io
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://docs.sunleibest.com

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'docs/.vuepress/dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

    # - name: Deploy to Server
    #   uses: easingthemes/ssh-deploy@main
    #   env:
    #       SSH_PRIVATE_KEY: ${{ secrets.TS_DEPLOY_KEY }}
    #       ARGS: "-rlgoDzvc -i "
    #       SOURCE: "docs/.vuepress/dist/"
    #       REMOTE_HOST: ${{ secrets.TS_DEPLOY_HOST }}
    #       REMOTE_USER: ${{ secrets.TS_DEPLOY_USER }}
    #       TARGET: ${{ secrets.TS_DEPLOY_PATH }}
    #       EXCLUDE: "/dist/, /node_modules/"